--- #YAML:1.0
name:                   CPAN-Testers
version:                0.06
abstract:               QA of CPAN distributions via cross-platform testing
author:
    - Adam J. Foxson <afoxson@pobox.com>
    - Barbie <barbie@missbarbell.co.uk>
    - David Golden <dagolden@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
build_requires:
  IO::File:               0
  Test::More:             0.70
requires:
  perl:                   5.006
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08

provides:
  CPAN::Testers:
    file:     lib/CPAN/Testers.pm
    version:  0.06
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers
  homepage:   http://www.cpantesters.org
  repository: http://github.com/barbie/cpan-testers

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
