--- #YAML:1.0
name:                CPAN-Testers
version:             0.02
abstract:            QA of CPAN distributions via cross-platform testing
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam J. Foxson <afoxson@pobox.com>
