--- #YAML:1.0
name:               CPAN-Testers
version:            0.03
abstract:           QA of CPAN distributions via cross-platform testing
author:
    - Adam J. Foxson <afoxson@pobox.com>, Barbie <barbie@missbarbell.co.uk>, David Golden <dagolden@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
